ALTER TABLE releases
ADD COLUMN IF NOT EXISTS source_title TEXT NOT NULL DEFAULT '';

ALTER TABLE releases
ADD COLUMN IF NOT EXISTS deobfuscated_title TEXT NOT NULL DEFAULT '';

ALTER TABLE releases
ADD COLUMN IF NOT EXISTS classification TEXT NOT NULL DEFAULT '';

ALTER TABLE releases
ADD COLUMN IF NOT EXISTS match_confidence DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE releases
ADD COLUMN IF NOT EXISTS identity_status TEXT NOT NULL DEFAULT 'unknown';

ALTER TABLE releases
ADD COLUMN IF NOT EXISTS group_name TEXT;

UPDATE releases
SET group_name = release_key
WHERE group_name IS NULL OR group_name = '';

ALTER TABLE releases
ALTER COLUMN group_name SET NOT NULL;

ALTER TABLE releases
ADD COLUMN IF NOT EXISTS passworded BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE releases
ADD COLUMN IF NOT EXISTS passworded_known BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE releases
ADD COLUMN IF NOT EXISTS passworded_unknown BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE releases
ADD COLUMN IF NOT EXISTS password_state TEXT NOT NULL DEFAULT 'not_passworded';

ALTER TABLE releases
ADD COLUMN IF NOT EXISTS preferred_password_id BIGINT;

ALTER TABLE releases
ADD COLUMN IF NOT EXISTS encrypted BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE releases
ADD COLUMN IF NOT EXISTS has_par2 BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE releases
ADD COLUMN IF NOT EXISTS has_nfo BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE releases
ADD COLUMN IF NOT EXISTS archive_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE releases
ADD COLUMN IF NOT EXISTS video_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE releases
ADD COLUMN IF NOT EXISTS audio_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE releases
ADD COLUMN IF NOT EXISTS sample_present BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE releases
ADD COLUMN IF NOT EXISTS availability_score DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE releases
ADD COLUMN IF NOT EXISTS availability_tier TEXT NOT NULL DEFAULT 'low';

ALTER TABLE releases
ADD COLUMN IF NOT EXISTS media_quality_score DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE releases
ADD COLUMN IF NOT EXISTS media_quality_tier TEXT NOT NULL DEFAULT 'unknown';

ALTER TABLE releases
ADD COLUMN IF NOT EXISTS identity_confidence_score DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE releases
ADD COLUMN IF NOT EXISTS runtime_seconds INTEGER NOT NULL DEFAULT 0;

ALTER TABLE releases
ADD COLUMN IF NOT EXISTS primary_resolution TEXT NOT NULL DEFAULT '';

ALTER TABLE releases
ADD COLUMN IF NOT EXISTS primary_video_codec TEXT NOT NULL DEFAULT '';

ALTER TABLE releases
ADD COLUMN IF NOT EXISTS primary_audio_codec TEXT NOT NULL DEFAULT '';

ALTER TABLE releases
ADD COLUMN IF NOT EXISTS subtitle_languages_json JSONB NOT NULL DEFAULT '[]'::jsonb;

ALTER TABLE releases
ADD COLUMN IF NOT EXISTS media_tags_json JSONB NOT NULL DEFAULT '[]'::jsonb;

ALTER TABLE releases
ADD COLUMN IF NOT EXISTS metadata_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE releases
DROP CONSTRAINT IF EXISTS releases_provider_id_release_key_key;

CREATE UNIQUE INDEX IF NOT EXISTS idx_releases_provider_group_name
ON releases(provider_id, group_name);
