ALTER TABLE binaries
ADD COLUMN IF NOT EXISTS file_index INTEGER NOT NULL DEFAULT 0;

ALTER TABLE binaries
ADD COLUMN IF NOT EXISTS expected_file_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE releases
ADD COLUMN IF NOT EXISTS expected_file_count INTEGER NOT NULL DEFAULT 0;
