ALTER TABLE releases
    ADD COLUMN IF NOT EXISTS matched_media_title TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS title_source TEXT NOT NULL DEFAULT 'source',
    ADD COLUMN IF NOT EXISTS title_confidence DOUBLE PRECISION NOT NULL DEFAULT 0;
