ALTER TABLE releases
ADD COLUMN IF NOT EXISTS season_number INTEGER NOT NULL DEFAULT 0;

ALTER TABLE releases
ADD COLUMN IF NOT EXISTS episode_number INTEGER NOT NULL DEFAULT 0;

ALTER TABLE releases
ADD COLUMN IF NOT EXISTS season_episode_source TEXT NOT NULL DEFAULT '';

ALTER TABLE releases
ADD COLUMN IF NOT EXISTS season_episode_confidence DOUBLE PRECISION NOT NULL DEFAULT 0;
