ALTER TABLE predb_entries
ADD COLUMN IF NOT EXISTS external_id BIGINT NOT NULL DEFAULT 0;

ALTER TABLE predb_entries
ADD COLUMN IF NOT EXISTS team TEXT NOT NULL DEFAULT '';

ALTER TABLE predb_entries
ADD COLUMN IF NOT EXISTS genre TEXT NOT NULL DEFAULT '';

ALTER TABLE predb_entries
ADD COLUMN IF NOT EXISTS url TEXT NOT NULL DEFAULT '';

ALTER TABLE predb_entries
ADD COLUMN IF NOT EXISTS size_kb DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE predb_entries
ADD COLUMN IF NOT EXISTS file_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE predb_entries
ADD COLUMN IF NOT EXISTS payload_json JSONB NOT NULL DEFAULT '{}'::jsonb;

CREATE UNIQUE INDEX IF NOT EXISTS idx_predb_entries_source_external_id
ON predb_entries(source, external_id)
WHERE external_id > 0;

ALTER TABLE release_predb_matches
ADD COLUMN IF NOT EXISTS chosen BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE release_predb_matches
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
