ALTER TABLE binaries
ADD COLUMN IF NOT EXISTS recovered_kind TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS recovered_extension TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS recovered_source TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS recovered_confidence DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS recovered_at TIMESTAMPTZ;
