CREATE TABLE IF NOT EXISTS public.binary_par2_targets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    binary_id bigint NOT NULL REFERENCES public.binaries(id) ON DELETE CASCADE,
    release_id text NOT NULL DEFAULT ''::text,
    file_name text NOT NULL,
    file_size bigint NOT NULL DEFAULT 0,
    metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    UNIQUE (binary_id, file_name)
);

CREATE INDEX IF NOT EXISTS idx_binary_par2_targets_file_name
    ON public.binary_par2_targets (lower(btrim(file_name)))
    WHERE btrim(file_name) <> '';

CREATE INDEX IF NOT EXISTS idx_binary_par2_targets_release_id
    ON public.binary_par2_targets (release_id)
    WHERE btrim(release_id) <> '';
